"use client";

import { createClient } from "@supabase/supabase-js";
import { useState } from "react";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [supabase] = useState(() =>
    createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    )
  );

  const signUp = async () => {
    const { data, error } = await supabase.auth.signUp({
      email: "11dionang@gmail.com",
      password: "sup3rs3cur3",
    });

    console.log(data);
    console.log(error);
  };

  const signIn = () => {
    supabase.auth.signInWithPassword({
      email: "dion@gmail.com",
      password: "dion",
    });
  };

  const signOut = () => {
    supabase.auth.signOut();
  };
  return (
    <html lang="en">
      <body>
        <button onClick={signUp}>Sign Up</button>
        <button onClick={signIn}>Sign In</button>
        <button onClick={signOut}>Sign Out</button>
        {children}
      </body>
    </html>
  );
}
