import "./globals.css";
import SupabaseProvider from "../lib/supabase/supabase-provider";
import Login from "@/components/Login";
import Chat from "@/components/Chat";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <Login />
          <Chat />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
