import "./globals.css";
import SupabaseProvider from "../components/providers/supabase-provider";
import SupabaseAuthProvider from "@/components/providers/supabase-auth-provider";
import { createServerClient } from "@/utils/supabase-server";
// import { Provider } from "react-redux";
// import store from "../redux/store";
import { Providers } from "@/components/providers/redux-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en" className="h-full scroll-smooth">
      <body className="h-full bg-neutral-950 text-neutral-50;">
        <SupabaseProvider>
          <Providers>
            <SupabaseAuthProvider serverSession={session}>
              {children}
            </SupabaseAuthProvider>
          </Providers>
        </SupabaseProvider>
      </body>
    </html>
  );
}
